version: '3'

volumes:
  db-data:

services:
  db:
    container_name: "tweets_db"
    image: postgres:16.2-bullseye
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    ports:
        - "5432:5432"
    healthcheck:
      test: pg_isready -U admin -h localhost -p 5432 --timeout=5
      interval: 6s
      timeout: 5s
      retries: 5
      start_period: 3s
