<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP9Wuh8j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP9Wuh8j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP9Wuh8j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP9Wuh8j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP9Wuh8j\App_KernelDevDebugContainer([
    'container.build_hash' => 'P9Wuh8j',
    'container.build_id' => '0a6fbc14',
    'container.build_time' => 1719600955,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP9Wuh8j');
