<?php

namespace ContainerUWTING1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPessoaControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CgrFaNd.App\Controller\PessoaController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.CgrFaNd'] ?? $container->load('get_ServiceLocator_CgrFaNdService'));

        if (isset($container->privates['.service_locator.CgrFaNd.App\\Controller\\PessoaController::delete()'])) {
            return $container->privates['.service_locator.CgrFaNd.App\\Controller\\PessoaController::delete()'];
        }

        return $container->privates['.service_locator.CgrFaNd.App\\Controller\\PessoaController::delete()'] = $a->withContext('App\\Controller\\PessoaController::delete()', $container);
    }
}
