<?php

namespace ContainerUWTING1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPessoaControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E7DSjsG.App\Controller\PessoaController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E7DSjsG.App\\Controller\\PessoaController::index()'] = ($container->privates['.service_locator.E7DSjsG'] ?? $container->load('get_ServiceLocator_E7DSjsGService'))->withContext('App\\Controller\\PessoaController::index()', $container);
    }
}
