<?php

namespace ContainerP9Wuh8j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C4YwfthService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c4Ywfth' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c4Ywfth'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\PessoaController::delete' => ['privates', '.service_locator.CgrFaNd.App\\Controller\\PessoaController::delete()', 'getPessoaControllerdeleteService', true],
            'App\\Controller\\PessoaController::edit' => ['privates', '.service_locator.CgrFaNd.App\\Controller\\PessoaController::edit()', 'getPessoaControllereditService', true],
            'App\\Controller\\PessoaController::index' => ['privates', '.service_locator.E7DSjsG.App\\Controller\\PessoaController::index()', 'getPessoaControllerindexService', true],
            'App\\Controller\\PessoaController::new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\PessoaController::new()', 'getPessoaControllernewService', true],
            'App\\Controller\\PessoaController::show' => ['privates', '.service_locator.E7DSjsG.App\\Controller\\PessoaController::show()', 'getPessoaControllershowService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Controller\\PessoaController:delete' => ['privates', '.service_locator.CgrFaNd.App\\Controller\\PessoaController::delete()', 'getPessoaControllerdeleteService', true],
            'App\\Controller\\PessoaController:edit' => ['privates', '.service_locator.CgrFaNd.App\\Controller\\PessoaController::edit()', 'getPessoaControllereditService', true],
            'App\\Controller\\PessoaController:index' => ['privates', '.service_locator.E7DSjsG.App\\Controller\\PessoaController::index()', 'getPessoaControllerindexService', true],
            'App\\Controller\\PessoaController:new' => ['privates', '.service_locator.P.blNFL.App\\Controller\\PessoaController::new()', 'getPessoaControllernewService', true],
            'App\\Controller\\PessoaController:show' => ['privates', '.service_locator.E7DSjsG.App\\Controller\\PessoaController::show()', 'getPessoaControllershowService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
        ], [
            'App\\Controller\\PessoaController::delete' => '?',
            'App\\Controller\\PessoaController::edit' => '?',
            'App\\Controller\\PessoaController::index' => '?',
            'App\\Controller\\PessoaController::new' => '?',
            'App\\Controller\\PessoaController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PessoaController:delete' => '?',
            'App\\Controller\\PessoaController:edit' => '?',
            'App\\Controller\\PessoaController:index' => '?',
            'App\\Controller\\PessoaController:new' => '?',
            'App\\Controller\\PessoaController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
