<?php

namespace ContainerP9Wuh8j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPessoaControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E7DSjsG.App\Controller\PessoaController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E7DSjsG.App\\Controller\\PessoaController::show()'] = ($container->privates['.service_locator.E7DSjsG'] ?? $container->load('get_ServiceLocator_E7DSjsGService'))->withContext('App\\Controller\\PessoaController::show()', $container);
    }
}
